# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install the latest version of uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - run: uv pip install pip
      - name: Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller
      - name: Test with pytest
        run: |
          pytest
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --console --collect-all click --name indu_doc src/indu_doc/cli.py
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: indu_doc-executable
          path: dist/indu_doc.exe
